DROP TABLE "B_USER_INFO";

CREATE TABLE "B_USER_INFO" (
	"USER_ID"	VARCHAR2(200)		NOT NULL,
	"USER_PASSWORD"	VARCHAR2(200)		NOT NULL,
	"KOR_NAME"	VARCHAR2(200)		NOT NULL,
	"BIRTHDATE"	VARCHAR2(200)		NOT NULL,
	"GENDER"	VARCHAR2(200)		NOT NULL,
	"TELECOM"	VARCHAR2(200)		NOT NULL,
	"PHONE_NO"	VARCHAR2(200)		NOT NULL,
	"EMAIL"	VARCHAR2(200)		NOT NULL,
	"SIGNUP_TYPE"	VARCHAR2(200)		NOT NULL,
	"REG_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL
);

COMMENT ON COLUMN "B_USER_INFO"."GENDER" IS '1~9';

COMMENT ON COLUMN "B_USER_INFO"."SIGNUP_TYPE" IS '웹/카카오';

DROP TABLE "B_DEPOSIT";

CREATE TABLE "B_DEPOSIT" (
	"D_CODE"	VARCHAR2(200)		NOT NULL,
	"D_NAME"	VARCHAR2(200)		NOT NULL,
	"D_INTEREST"	NUMBER(3,1)		NOT NULL,
	"D_SALE_STATUS"	VARCHAR2(100)	DEFAULT '판매'	NOT NULL,
	"D_DETAIL"	CLOB		NOT NULL
);

DROP TABLE "B_TRANSFER";

CREATE TABLE "B_TRANSFER" (
	"T_NO"	NUMBER		NOT NULL,
	"ACCOUNT_NO"	NUMBER		NOT NULL,
	"T_AMOUNT"	NUMBER		NOT NULL,
	"T_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	"T_TIME"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'HH24:MI:SS')	NOT NULL,
	"T_TYPE"	NUMBER		NULL,
	"T_PREVIOUS_BALANCE"	NUMBER		NOT NULL,
	"T_TO_MEMO"	VARCHAR2(45)		NULL,
	"T_FROM_MEMO"	VARCHAR2(45)		NULL,
	"T_INFO"	VARCHAR2(45)		NOT NULL
);

COMMENT ON COLUMN "B_TRANSFER"."T_TYPE" IS '오픈뱅킹/당행/타행';

COMMENT ON COLUMN "B_TRANSFER"."T_TO_MEMO" IS '7자이내';

COMMENT ON COLUMN "B_TRANSFER"."T_FROM_MEMO" IS '7자이내';

COMMENT ON COLUMN "B_TRANSFER"."T_INFO" IS '거래내용';

DROP TABLE "B_USER_AUTHORITY";

CREATE TABLE "B_USER_AUTHORITY" (
	"ROLE_CODE"	VARCHAR2(100)		NOT NULL,
	"ROLE_NAME"	VARCHAR2(100)		NOT NULL,
	"USER_ID"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "B_USER_AUTHORITY"."ROLE_CODE" IS 'A758, H1, H2, H3';

COMMENT ON COLUMN "B_USER_AUTHORITY"."ROLE_NAME" IS '관리자, 골드, 실버, 브론즈';

DROP TABLE "B_USER_ACCOUNT";

CREATE TABLE "B_USER_ACCOUNT" (
	"ACCOUNT_NO"	NUMBER		NOT NULL,
	"CREATED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"LASTNAME"	VARCHAR2(200)		NOT NULL,
	"FIRSTNAME"	VARCHAR2(200)		NOT NULL,
	"ACCOUNT_PASSWORD"	INTEGER		NOT NULL,
	"TOTAL_BALANCE"	NUMBER		NOT NULL,
	"BENEFIT_CODE"	VARCHAR2(200)		NULL,
	"ACCOUNT_NICKNAME"	VARCHAR2(200)		NULL,
	"TRANSFER_ONCE_LIMIT"	NUMBER		NOT NULL,
	"TRANSFER_DAY_LIMIT"	NUMBER		NOT NULL,
	"S_CODE"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(200)		NOT NULL,
	"OP_BANK_CODE"	VARCHAR2(200)		NOT NULL
);

COMMENT ON COLUMN "B_USER_ACCOUNT"."ACCOUNT_PASSWORD" IS '숫자4자리';

COMMENT ON COLUMN "B_USER_ACCOUNT"."TRANSFER_ONCE_LIMIT" IS '등급별/이용별';

DROP TABLE "B_COMMENT";

CREATE TABLE "B_COMMENT" (
	"C_NO"	NUMBER		NOT NULL,
	"COMMENTS"	VARCHAR2(1800)		NULL,
	"REG_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	"Q_NO"	NUMBER		NOT NULL,
	"Q_ID"	VARCHAR2(200)		NOT NULL,
	"Q_NO2"	NUMBER		NOT NULL
);

DROP TABLE "B_NOTICE_FNQ";

CREATE TABLE "B_NOTICE_FNQ" (
	"N_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(200)		NOT NULL,
	"N_TITLE"	VARCHAR2(200)		NOT NULL,
	"N_CONTENTS"	CLOB		NOT NULL,
	"N_REG_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	"N_HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"N_CATEGORY"	VARCHAR2(200)		NULL
);

DROP TABLE "B_QNA";

CREATE TABLE "B_QNA" (
	"Q_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(200)		NOT NULL,
	"Q_TITLE"	VARCHAR2(200)		NOT NULL,
	"Q_CONTENTS"	CLOB		NOT NULL,
	"Q_REG_DATE"	VARCHAR2(200)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	"Q_HIT"	NUMBER	DEFAULT 0	NOT NULL
);

DROP TABLE "B_USER_ADDRESS";

CREATE TABLE "B_USER_ADDRESS" (
	"USER_ID"	VARCHAR2(200)		NOT NULL,
	"ADDRESS_TYPE"	VARCHAR2(200)		NOT NULL,
	"POSTCODE"	NUMBER(5)		NOT NULL,
	"ROAD_ADDRESS"	VARCHAR2(200)		NULL,
	"DEATIL_ADDRESS"	VARCHAR2(200)		NULL
);

COMMENT ON COLUMN "B_USER_ADDRESS"."ADDRESS_TYPE" IS '자택/직장';

DROP TABLE "B_NOTICE_IMG";

CREATE TABLE "B_NOTICE_IMG" (
	"파일번호"	NUMBER		NOT NULL,
	"글번호"	NUMBER		NOT NULL,
	"파일명"	VARCHAR2(200)		NULL
);

DROP TABLE "B_OPENBANK";

CREATE TABLE "B_OPENBANK" (
	"OP_BANK_CODE"	VARCHAR2(200)		NOT NULL,
	"OP_BANK_NAME"	VARCHAR2(200)		NOT NULL,
	"OP_BANK_ACCOUNT"	INTEGER		NOT NULL,
	"USER_ID"	VARCHAR2(200)		NOT NULL
);

ALTER TABLE "B_USER_INFO" ADD CONSTRAINT "PK_B_USER_INFO" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "B_DEPOSIT" ADD CONSTRAINT "PK_B_DEPOSIT" PRIMARY KEY (
	"D_CODE"
);

ALTER TABLE "B_TRANSFER" ADD CONSTRAINT "PK_B_TRANSFER" PRIMARY KEY (
	"T_NO"
);

ALTER TABLE "B_USER_AUTHORITY" ADD CONSTRAINT "PK_B_USER_AUTHORITY" PRIMARY KEY (
	"ROLE_CODE"
);

ALTER TABLE "B_USER_ACCOUNT" ADD CONSTRAINT "PK_B_USER_ACCOUNT" PRIMARY KEY (
	"ACCOUNT_NO"
);

ALTER TABLE "B_COMMENT" ADD CONSTRAINT "PK_B_COMMENT" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "B_NOTICE_FNQ" ADD CONSTRAINT "PK_B_NOTICE_FNQ" PRIMARY KEY (
	"N_NO"
);

ALTER TABLE "B_QNA" ADD CONSTRAINT "PK_B_QNA" PRIMARY KEY (
	"Q_NO"
);

ALTER TABLE "B_USER_ADDRESS" ADD CONSTRAINT "PK_B_USER_ADDRESS" PRIMARY KEY (
	"USER_ID"
);

ALTER TABLE "B_NOTICE_IMG" ADD CONSTRAINT "PK_B_NOTICE_IMG" PRIMARY KEY (
	"파일번호",
	"글번호"
);

ALTER TABLE "B_OPENBANK" ADD CONSTRAINT "PK_B_OPENBANK" PRIMARY KEY (
	"OP_BANK_CODE"
);

ALTER TABLE "B_USER_ADDRESS" ADD CONSTRAINT "FK_B_USER_INFO_TO_B_USER_ADDRESS_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "B_USER_INFO" (
	"USER_ID"
);

ALTER TABLE "B_NOTICE_IMG" ADD CONSTRAINT "FK_B_NOTICE_FNQ_TO_B_NOTICE_IMG_1" FOREIGN KEY (
	"글번호"
)
REFERENCES "B_NOTICE_FNQ" (
	"N_NO"
);
