SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') AS CURRENT_DATE_TIME FROM dual;

SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') AS CURRENT_DATE_TIME FROM dual;

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS CURRENT_DATE_TIME FROM dual;

CREATE SEQUENCE SEQ_BOOKLIST_NO START WITH 230001 NOCACHE;
INSERT INTO BOOKLIST(NO, TITLE, AUTHOR, PUBLISHER, STOCK)
            VALUES(SEQ_BOOKLIST_NO.NEXTVAL, '어떤 책이 가장 읽기 좋을까?', '김작가', '민음사', 2);



CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;
CREATE SEQUENCE SEQ_QNA_NO NOCACHE;
CREATE SEQUENCE SEQ_FNQ_NO NOCACHE;



--조회용
SELECT * FROM B_BOARD ORDER BY P_NO DESC;
SELECT * FROM B_USER_INFO;
SELECT * FROM B_USER_AUTHORITY;
SELECT * FROM B_DEPOSIT;
SELECT * FROM B_USER_ACCOUNT;
SELECT * FROM B_USER_ADDRESS;


COMMIT;

--임의등록
INSERT INTO B_USER_AUTHORITY(ROLE_CODE, ROLE_NAME) VALUES('A758', '관리자');
INSERT INTO B_USER_AUTHORITY(ROLE_CODE, ROLE_NAME) VALUES('H1', '골드');
INSERT INTO B_USER_AUTHORITY(ROLE_CODE, ROLE_NAME) VALUES('H2', '실버');
INSERT INTO B_USER_AUTHORITY(ROLE_CODE, ROLE_NAME) VALUES('H3', '브론즈');


--회원
INSERT INTO B_USER_INFO(USER_ID, USER_PASSWORD, KOR_NAME, BIRTHDATE, GENDER, TELECOM, PHONE_NO, EMAIL, SIGNUP_TYPE, ROLE_CODE)
                VALUES('aaaa', '1111', '김테스트', '901208', '2', 'SKT', '01083499438', 'aaaa@naver.com', 'web', 'H3');

INSERT INTO B_USER_ADDRESS(USER_ID, ADDRESS_TYPE, POSTCODE, ROAD_ADDRESS, DETAIL_ADDRESS)
          VALUES('aaaa', '자택', '13073', '경기도 성남시 수정로', '한울관B309');

--QNA                
INSERT INTO B_BOARD(P_NO, USER_ID, P_TITLE, P_CONTENTS) VALUES(SEQ_QNA_NO.NEXTVAL, 'aaaa', '제목입니다', '내용이 많습니다');

--상품신규
INSERT INTO B_DEPOSIT(D_PRODUCT_CODE, D_PRODUCT_NAME, D_INTEREST, D_SALE_STATUS, D_DETAIL) VALUES('S1', 'HR하리사랑통장', 0.5, 'Y', '출금·이체수수료 횟수제한 없이 면제!');
COMMIT;

--계좌신규
--INSERT INTO B_USER_ACCOUNT(ACCOUNT_NO, LASTNAME, FIRSTNAME, ACCOUNT_PASSWORD, TOTAL_BALANCE_BENEFIT_CODE, ACCOUNT_NICKNAME, TRANSFER_ONCE_LIMIT, TRANSFER_DAY_LIMIT, S_CODE, USER_ID, OP_BANK_CODE)
--                    VALUES(계좌번호 시퀀스);





--중복검사 로직                
SELECT COUNT(*) FROM B_USER_INFO WHERE USER_ID='aaaa';

--로그인 정보 확인
SELECT * FROM B_USER_INFO WHERE USER_ID = 'test' AND USER_PASSWORD = '1111';

--회원 전체 정보까지.
SELECT UI.USER_ID, UI.USER_PASSWORD, UI.KOR_NAME, UI.BIRTHDATE, UI.GENDER, UI.TELECOM, UI.PHONE_NO, UI.EMAIL,
       UA.POSTCODE, UA.ROAD_ADDRESS, UA.DETAIL_ADDRESS
FROM B_USER_INFO UI
LEFT JOIN B_USER_ADDRESS UA ON UI.USER_ID = UA.USER_ID
WHERE UI.USER_ID = 'aaaa';


--회원정보 찾기
SELECT * FROM B_USER_INFO WHERE USER_ID = 'aaaa';

--삭제
DELETE B_USER_INFO WHERE USER_ID='test2';